name: 'Update CI'
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  update: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: ./
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Update README.md
